name: Publish

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [15, 14, 12]

    steps:
      - name: 📫 Check mailbox
        uses: actions/checkout@v2

      - name: 🪂 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: 📦 Obtain details
        run: npm install
      
      - name: 📋 Deliver prognosis
        run: npm test

  publish:
    name: Publish
    needs: test
    if: github.repository == 'TinkerStorm/validate'
    runs-on: ubuntu-latest

    steps:
      - name: 📫 Check mailbox
        uses: actions/checkout@v2

      - name: 🪂 Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - name: 📦 Publish (NPM)
        uses: pascalgn/npm-publish-action@1.3.6
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^Release (\\S+)"
          publish_args: "--non-interactive --verbose"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}