name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 15
          # LTS
          - 14
          - 12
    
    steps:
      - name: 📫 Check mailbox
        uses: actions/checkout@v2

      - name: 🪂 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: 📦 Obtain details
        run: npm install
      
      - name: 📋 Deliver prognosis
        run: npm test